[package]
name = "graphics_markup_language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.25.0"
strum_macros = "0.25.3"
colored = "2.1.0"
resvg = "0.37.0"
