mod color_parser;
mod i16_parser;
mod u8_parser;

use crate::draw_elements::*;

#[allow(unused)]
enum MainStates {
    Start,
    MainStart(Main),
    MainVisibleExtent(Main),
    MainVisibleExtentStart(Main),
    MainVisibleExtentX(Main),
    MainVisibleExtentXEnd(Main),
    MainVisibleExtentY(Main),
    MainVisibleExtentYEnd(Main),
    MainVisibleExtentEnd(Main),
    MainBackgroundColor(Main),
    MainBackgroundColorStart(Main),
    MainBackgroundColorRed(Main),
    MainBackgroundColorRedEnd(Main),
    MainBackgroundColorGreen(Main),
    MainBackgroundColorGreenEnd(Main),
    MainBackgroundColorBlue(Main),
    MainBackgroundColorBlueEnd(Main),
    MainBackgroundColorEnd(Main),
    MainShapes(Main),
    MainShapesStart(Main),
    MainShapesElementStart(Main, AmbiguousElement),
    MainShapesElementPosition(Main, AmbiguousElement),
    MainShapesElementPositionStart(Main, AmbiguousElement),
    MainShapesElementPositionX(Main, AmbiguousElement),
    MainShapesElementPositionXEnd(Main, AmbiguousElement),
    MainShapesElementPositionY(Main, AmbiguousElement),
    MainShapesElementPositionYEnd(Main, AmbiguousElement),
    MainShapesElementPositionEnd(Main, AmbiguousElement),
    MainShapesElementRotation(Main, AmbiguousElement),
    MainShapesElementRotationEnd(Main, AmbiguousElement),
    MainShapesPolygonWidth(Main, Polygon),
    MainShapesPolygonWidthEnd(Main, Polygon),
    MainShapesPolygonBorderColor(Main, Polygon),
    MainShapesPolygonBorderColorStart(Main, Polygon),
    MainShapesPolygonBorderColorRed(Main, Polygon),
    MainShapesPolygonBorderColorRedEnd(Main, Polygon),
    MainShapesPolygonBorderColorGreen(Main, Polygon),
    MainShapesPolygonBorderColorGreenEnd(Main, Polygon),
    MainShapesPolygonBorderColorBlue(Main, Polygon),
    MainShapesPolygonBorderColorBlueEnd(Main, Polygon),
    MainShapesPolygonBorderColorEnd(Main, Polygon),
    MainShapesPolygonFillColor(Main, Polygon),
    MainShapesPolygonFillColorStart(Main, Polygon),
    MainShapesPolygonFillColorRed(Main, Polygon),
    MainShapesPolygonFillColorRedEnd(Main, Polygon),
    MainShapesPolygonFillColorGreen(Main, Polygon),
    MainShapesPolygonFillColorGreenEnd(Main, Polygon),
    MainShapesPolygonFillColorBlue(Main, Polygon),
    MainShapesPolygonFillColorBlueEnd(Main, Polygon),
    MainShapesPolygonFillColorEnd(Main, Polygon),
    MainShapesPolygonVertices(Main, Polygon),
    MainShapesPolygonVerticesStart(Main, Polygon),
    MainShapesPolygonVerticesVertexStart(Main, Polygon),
    MainShapesPolygonVerticesVertexX(Main, Polygon, Point),
    MainShapesPolygonVerticesVertexXEnd(Main, Polygon, Point),
    MainShapesPolygonVerticesVertexY(Main, Polygon, Point),
    MainShapesPolygonVerticesVertexYEnd(Main, Polygon, Point),
    MainShapesPolygonVerticesEnd(Main, Polygon),
    MainShapesGroupShapes(Main, Group),
    MainShapesGroupShapesStart(Main, Group),
    MainShapesGroupShapesPolygonStart(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPosition(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionStart(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionX(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionXEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionY(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionYEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonPositionEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonRotation(Main, Group, Polygon),
    MainShapesGroupShapesPolygonRotationEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonWidth(Main, Group, Polygon),
    MainShapesGroupShapesPolygonWidthEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColor(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorStart(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorRed(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorRedEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorGreen(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorGreenEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorBlue(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorBlueEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonBorderColorEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColor(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorStart(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorRed(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorRedEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorGreen(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorGreenEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorBlue(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorBlueEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonFillColorEnd(Main, Group, Polygon),
    MainShapesGroupShapesPolygonVertices(Main, Group, Polygon),
    MainShapesGroupShapesPolygonVerticesStart(Main, Group, Polygon),
    MainShapesGroupShapesPolygonVerticesVertexStart(Main, Group, Polygon, Point),
    MainShapesGroupShapesPolygonVerticesVertexX(Main, Group, Polygon, Point),
    MainShapesGroupShapesPolygonVerticesVertexXEnd(Main, Group, Polygon, Point),
    MainShapesGroupShapesPolygonVerticesVertexY(Main, Group, Polygon, Point),
    MainShapesGroupShapesPolygonVerticesVertexYEnd(Main, Group, Polygon, Point),
    MainShapesGroupShapesPolygonVerticesEnd(Main, Group, Polygon),
    MainShapesGroupShapesEnd(Main, Group),
    MainShapesEnd(Main),
    MainEnd(Main),
}

#[cfg(test)]
mod tests {}
